# Generated by Django 5.0.4 on 2024-04-25 05:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_reviewitem_review_alter_guideline_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='guideline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='reviewitem',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
