# Generated by Django 5.0.4 on 2024-04-25 19:40

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_content_created_at_guideline_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='file',
            field=models.FileField(upload_to=core.models.unique_file_name),
        ),
    ]
